-- comment: create the agents table as the core aggregate for the workforce management context
CREATE TABLE workforce.agents (
  id                          UUID            NOT NULL DEFAULT gen_random_uuid(),
  availability_status         VARCHAR(20)     NOT NULL DEFAULT 'OFFLINE',
  capability_class            VARCHAR(25)     NOT NULL,
  completed_delivery_count    INTEGER         NOT NULL DEFAULT 0,
  created_at                  TIMESTAMPTZ     NOT NULL,
  created_by                  VARCHAR(36)     NOT NULL,
  current_h3_index            VARCHAR(20),
  current_latitude            NUMERIC(10,8),
  current_longitude           NUMERIC(11,8),
  current_orders              INTEGER NOT NULL DEFAULT 0 CHECK (current_orders >= 0),
  email                       VARCHAR(255),
  first_name                  VARCHAR(100)    NOT NULL,
  last_location_updated_at    TIMESTAMPTZ,
  last_name                   VARCHAR(100)    NOT NULL,
  location_source             VARCHAR(20),
  max_concurrent_orders       SMALLINT        NOT NULL,
  national_id_number          VARCHAR(20)     NOT NULL,
  national_id_type            VARCHAR(20)     NOT NULL DEFAULT 'NATIONAL_ID',
  on_time_delivery_count      INTEGER         NOT NULL DEFAULT 0 CHECK (on_time_delivery_count >= 0),
  phone_number                VARCHAR(20)     NOT NULL,
  alternate_phone_number      VARCHAR(20),
  rejection_reason            VARCHAR(1000),
  reliability_score           NUMERIC(5,2),
  updated_at                  TIMESTAMPTZ,
  updated_by                  VARCHAR(36),
  user_id                     VARCHAR(36)     NOT NULL,
  version                     BIGINT          NOT NULL DEFAULT 0,

  CONSTRAINT pk_agents
      PRIMARY KEY (id)
);

-- comment: add check constraints for the agents table
ALTER TABLE workforce.agents
    ADD CONSTRAINT chk_agents_availability_status
        CHECK (availability_status IN ('AVAILABLE', 'BUSY', 'DEACTIVATED', 'OFFLINE', 'PENDING', 'SUSPENDED', 'UNAVAILABLE'));

ALTER TABLE workforce.agents
    ADD CONSTRAINT chk_agents_capability_class
        CHECK (capability_class IN ('BICYCLE_RIDER', 'LIGHT_MOTOR_RIDER', 'VEHICLE_DRIVER'));

ALTER TABLE workforce.agents
    ADD CONSTRAINT chk_agents_completed_delivery_count
        CHECK (completed_delivery_count >= 0);

ALTER TABLE workforce.agents
    ADD CONSTRAINT chk_agents_location_source
        CHECK (location_source IS NULL OR location_source IN ('ITRACK_DEVICE', 'MOBILE_BROWSER', 'WEB_BROWSER'));

ALTER TABLE workforce.agents
    ADD CONSTRAINT chk_agents_max_concurrent_orders
        CHECK (max_concurrent_orders > 0);

ALTER TABLE workforce.agents
    ADD CONSTRAINT chk_agents_national_id_type
        CHECK (national_id_type IN ('NATIONAL_ID', 'PASSPORT'));

ALTER TABLE workforce.agents
    ADD CONSTRAINT chk_agents_phone_number
        CHECK (phone_number ~ '^\+[1-9]\d{1,14}$');

ALTER TABLE workforce.agents
    ADD CONSTRAINT chk_agents_alternate_phone_number
        CHECK (alternate_phone_number IS NULL OR alternate_phone_number ~ '^\+[1-9]\d{1,14}$');

ALTER TABLE workforce.agents
    ADD CONSTRAINT chk_agents_reliability_score
        CHECK (reliability_score IS NULL OR (reliability_score >= 0 AND reliability_score <= 100));

ALTER TABLE workforce.agents
    ADD CONSTRAINT chk_agents_location_fields_consistent
        CHECK (
            (current_latitude IS NULL AND current_longitude IS NULL AND current_h3_index IS NULL)
                OR
            (current_latitude IS NOT NULL AND current_longitude IS NOT NULL AND current_h3_index IS NOT NULL)
            );

-- comment: create indexes for the agents table
CREATE INDEX idx_agents_availability_status         ON workforce.agents (availability_status);
CREATE INDEX idx_agents_capability_class            ON workforce.agents (capability_class);
CREATE INDEX idx_agents_h3_index                   ON workforce.agents (current_h3_index);
CREATE INDEX idx_agents_availability_h3            ON workforce.agents (availability_status, current_h3_index);
CREATE UNIQUE INDEX uq_agents_email                ON workforce.agents (email) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX uq_agents_national_id_number   ON workforce.agents (national_id_number);
CREATE UNIQUE INDEX uq_agents_phone_number         ON workforce.agents (phone_number);
CREATE UNIQUE INDEX uq_agents_user_id ON workforce.agents (user_id);

-- comment: add table and column comments for the agents table
COMMENT ON TABLE workforce.agents IS
    'Core aggregate for the workforce management context. Owns agent identity, availability, '
        'and denormalised current location for hot-path eligibility queries. '
        'Suspension history is tracked in the suspensions table. '
        'Vehicle assignment is owned by Vehicle Management context.';

COMMENT ON COLUMN workforce.agents.id                        IS 'Primary key - UUID generated by application, database default is safety net';
COMMENT ON COLUMN workforce.agents.alternate_phone_number    IS 'Optional emergency contact number. E.164 format';
COMMENT ON COLUMN workforce.agents.availability_status       IS 'Current availability state. SUSPENDED and DEACTIVATED are admin-initiated. DEACTIVATED is terminal';
COMMENT ON COLUMN workforce.agents.capability_class          IS 'Agent licensing and capacity tier. Determines required certifications and default max concurrent orders';
COMMENT ON COLUMN workforce.agents.completed_delivery_count  IS 'Cumulative completed deliveries. Gates reliability score computation - score is trusted at >= 5';
COMMENT ON COLUMN workforce.agents.created_at                IS 'Record creation timestamp in UTC - immutable';
COMMENT ON COLUMN workforce.agents.created_by                IS 'Keycloak user ID of admin who onboarded the agent - immutable';
COMMENT ON COLUMN workforce.agents.current_h3_index          IS 'H3 cell index at resolution 9 (~174m² cells). Updated atomically with coordinates. Primary index for k-ring proximity queries';
COMMENT ON COLUMN workforce.agents.current_latitude          IS 'Current latitude. Null until first location update. Always consistent with current_longitude and current_h3_index';
COMMENT ON COLUMN workforce.agents.current_longitude         IS 'Current longitude. Null until first location update. Always consistent with current_latitude and current_h3_index';
COMMENT ON COLUMN workforce.agents.current_orders            IS 'Current number of active orders. Always consistent with current_h3_index';
COMMENT ON COLUMN workforce.agents.email                     IS 'Optional. Many informal riders do not hold a personal email address';
COMMENT ON COLUMN workforce.agents.first_name                IS 'Agent first name';
COMMENT ON COLUMN workforce.agents.last_location_updated_at  IS 'Timestamp of most recent location update. Used to compute location freshness at query time';
COMMENT ON COLUMN workforce.agents.last_name                 IS 'Agent last name';
COMMENT ON COLUMN workforce.agents.location_source           IS 'Source of most recent location update. BROWSER_GPS at MVP via mobile browser. ITRACK_DEVICE post-MVP via Vehicle Management';
COMMENT ON COLUMN workforce.agents.max_concurrent_orders     IS 'Configurable per agent. Defaults at creation: BICYCLE_RIDER=2, LIGHT_MOTOR_RIDER=3, VEHICLE_DRIVER=5';
COMMENT ON COLUMN workforce.agents.national_id_number        IS 'Kenya national ID: 6-8 digit numeric. Passport: 6-9 alphanumeric. Unique across all agents';
COMMENT ON COLUMN workforce.agents.national_id_type          IS 'Document type backing the national_id_number field';
COMMENT ON COLUMN workforce.agents.on_time_delivery_count    IS 'Cumulative on-time deliveries. Gates reliability score computation - score is trusted at >= 5';
COMMENT ON COLUMN workforce.agents.phone_number              IS 'Primary contact number. E.164 format. Mandatory. Used for SMS and M-Pesa communications';
COMMENT ON COLUMN workforce.agents.reliability_score         IS 'Null for new agents - treated as 50.0 in assignment ranking until computed. Computed after 5 completed deliveries. Range 0-100';
COMMENT ON COLUMN workforce.agents.rejection_reason   IS 'Reason provided by checker on rejection - surfaced to submitter for resubmission guidance';
COMMENT ON COLUMN workforce.agents.updated_at                IS 'Timestamp of last state change in UTC';
COMMENT ON COLUMN workforce.agents.updated_by                IS 'Keycloak user ID of actor who performed the last state change';
COMMENT ON COLUMN workforce.agents.user_id                   IS 'Keycloak user ID of the agent themselves - maps the authenticated rider identity to their agent record. Distinct from created_by which is the admin who onboarded them';
COMMENT ON COLUMN workforce.agents.version                   IS 'Optimistic locking version for concurrent update control';