-- comment: create the suspensions table to maintain a complete history of agent suspensions
CREATE TABLE workforce.suspensions (
   id              UUID            NOT NULL DEFAULT gen_random_uuid(),
   agent_id        UUID            NOT NULL,
   created_at      TIMESTAMPTZ     NOT NULL,
   created_by      VARCHAR(36)     NOT NULL,
   expires_at      TIMESTAMPTZ,
   lifted_at       TIMESTAMPTZ,
   lifted_by       VARCHAR(36),
   notes           TEXT,
   reason          VARCHAR(255)     NOT NULL,
   updated_at      TIMESTAMPTZ,
   updated_by      VARCHAR(36),
   version         BIGINT          NOT NULL DEFAULT 0,

   CONSTRAINT pk_suspensions
       PRIMARY KEY (id),

   CONSTRAINT fk_suspensions_agent
       FOREIGN KEY (agent_id)
           REFERENCES workforce.agents (id)
           ON DELETE RESTRICT
);

ALTER TABLE workforce.suspensions
    ADD CONSTRAINT chk_suspensions_lifted_fields_consistent
        CHECK (
            (lifted_at IS NULL AND lifted_by IS NULL)
                OR
            (lifted_at IS NOT NULL AND lifted_by IS NOT NULL)
            );

ALTER TABLE workforce.suspensions
    ADD CONSTRAINT chk_suspensions_expires_after_created
        CHECK (expires_at IS NULL OR expires_at > created_at);

ALTER TABLE workforce.suspensions
    ADD CONSTRAINT chk_suspensions_lifted_after_created
        CHECK (lifted_at IS NULL OR lifted_at >= created_at);

-- comment: create indexes for the suspensions table
CREATE INDEX idx_suspensions_agent          ON workforce.suspensions (agent_id);
CREATE INDEX idx_suspensions_reason         ON workforce.suspensions (reason);
CREATE INDEX idx_suspensions_expires_at     ON workforce.suspensions (expires_at) WHERE expires_at IS NOT NULL;
CREATE UNIQUE INDEX uq_suspensions_agent_active
    ON workforce.suspensions (agent_id) WHERE lifted_at IS NULL;

-- comment: add table and column comments for the suspensions table
COMMENT ON TABLE workforce.suspensions IS
    'Complete history of agent suspensions. Each record represents one suspension event. '
        'A partial unique index on agent_id where lifted_at IS NULL enforces that only one active '
        'suspension can exist per agent at any time, at the database level.';

COMMENT ON COLUMN workforce.suspensions.id          IS 'Primary key - UUID generated by application, database default is safety net';
COMMENT ON COLUMN workforce.suspensions.agent_id    IS 'Foreign key to the suspended agent';
COMMENT ON COLUMN workforce.suspensions.created_at  IS 'Timestamp when suspension was initiated in UTC - immutable';
COMMENT ON COLUMN workforce.suspensions.created_by  IS 'Keycloak user ID of admin who initiated the suspension - immutable';
COMMENT ON COLUMN workforce.suspensions.expires_at  IS 'Scheduled expiry timestamp. Null indicates indefinite suspension requiring manual admin lift';
COMMENT ON COLUMN workforce.suspensions.lifted_at   IS 'Timestamp when suspension was lifted. Null while suspension is active';
COMMENT ON COLUMN workforce.suspensions.lifted_by   IS 'Keycloak user ID of admin who lifted the suspension. Null while suspension is active';
COMMENT ON COLUMN workforce.suspensions.notes       IS 'Optional free-text context for the suspension provided by the initiating admin';
COMMENT ON COLUMN workforce.suspensions.reason      IS 'Reason for suspension.';
COMMENT ON COLUMN workforce.suspensions.updated_at  IS 'Timestamp of last change in UTC - set when suspension is lifted';
COMMENT ON COLUMN workforce.suspensions.updated_by  IS 'Keycloak user ID of actor who performed the last change';
COMMENT ON COLUMN workforce.suspensions.version     IS 'Optimistic locking version for concurrent lift control';