-- comment: create a documents table to manage agent compliance and onboarding documentation
CREATE TABLE workforce.documents (
     id                      UUID            NOT NULL DEFAULT gen_random_uuid(),
     agent_id                UUID,
     created_at              TIMESTAMPTZ     NOT NULL,
     created_by              VARCHAR(36)     NOT NULL,
     document_type           VARCHAR(50)     NOT NULL,
     expiry_date             DATE,
     file_name               VARCHAR(255),
     file_size_bytes         BIGINT,
     file_storage_url        VARCHAR(1000),
     mime_type               VARCHAR(100),
     replaces_document_id    UUID,
     status                  VARCHAR(50)     NOT NULL DEFAULT 'PENDING',
     updated_at              TIMESTAMPTZ,
     updated_by              VARCHAR(36),
     uploaded_at             TIMESTAMPTZ,
     version                 BIGINT          NOT NULL DEFAULT 0,

     CONSTRAINT pk_documents
         PRIMARY KEY (id),

     CONSTRAINT fk_documents_agent
         FOREIGN KEY (agent_id)
             REFERENCES workforce.agents (id)
             ON DELETE RESTRICT,

     CONSTRAINT fk_documents_replaces
         FOREIGN KEY (replaces_document_id)
             REFERENCES workforce.documents (id)
             ON DELETE SET NULL
);

-- comment: add check constraints for the documents table
ALTER TABLE workforce.documents
    ADD CONSTRAINT chk_documents_document_type
        CHECK (document_type IN (
                                 'DRIVING_LICENSE_COPY',
                                 'NATIONAL_ID_BACK',
                                 'NATIONAL_ID_FRONT'
            ));

ALTER TABLE workforce.documents
    ADD CONSTRAINT chk_documents_status
        CHECK (status IN ('ACTIVE', 'EXPIRED', 'PENDING', 'REPLACED', 'UPLOADED'));

ALTER TABLE workforce.documents
    ADD CONSTRAINT chk_documents_file_storage_url_required
        CHECK (status = 'PENDING' OR file_storage_url IS NOT NULL);

-- comment: create indexes for the documents table
CREATE INDEX idx_documents_agent             ON workforce.documents (agent_id);
CREATE INDEX idx_documents_agent_type        ON workforce.documents (agent_id, document_type);
CREATE INDEX idx_documents_expiry_date       ON workforce.documents (expiry_date);
CREATE INDEX idx_documents_status            ON workforce.documents (status);
CREATE UNIQUE INDEX uq_documents_file_storage_url
    ON workforce.documents (file_storage_url) WHERE file_storage_url IS NOT NULL;
CREATE UNIQUE INDEX uq_documents_agent_type_active
    ON workforce.documents (agent_id, document_type) WHERE status = 'ACTIVE';

-- comment: add table and column comments for the documents table
COMMENT ON TABLE workforce.documents IS
    'Agent compliance and onboarding documents with lifecycle tracking. Documents begin as PENDING '
        'on upload initiation, transition to UPLOADED on client confirmation, ACTIVE on admin approval, '
        'REPLACED when a newer version supersedes them, and EXPIRED when their expiry date is reached. '
        'file_storage_url is required for all non-PENDING documents enforced via check constraint.';

COMMENT ON COLUMN workforce.documents.id                    IS 'Primary key - UUID generated by application, database default is safety net';
COMMENT ON COLUMN workforce.documents.agent_id              IS 'Foreign key to the agent who owns this document';
COMMENT ON COLUMN workforce.documents.created_at            IS 'Record creation timestamp in UTC - immutable';
COMMENT ON COLUMN workforce.documents.created_by            IS 'Keycloak user ID of the actor who initiated the upload - immutable';
COMMENT ON COLUMN workforce.documents.document_type         IS 'Type of compliance document uploaded during agent onboarding';
COMMENT ON COLUMN workforce.documents.expiry_date           IS 'Document expiration date - relevant for NTSA driving license and Good Conduct Certificate';
COMMENT ON COLUMN workforce.documents.file_name             IS 'Original filename of the uploaded document';
COMMENT ON COLUMN workforce.documents.file_size_bytes       IS 'File size in bytes - populated on upload confirmation';
COMMENT ON COLUMN workforce.documents.file_storage_url      IS 'S3 storage key where the document file is stored - required for all non-PENDING documents';
COMMENT ON COLUMN workforce.documents.mime_type             IS 'MIME type of the uploaded document file';
COMMENT ON COLUMN workforce.documents.replaces_document_id  IS 'Self-referential FK to the document this record supersedes - null for original submissions';
COMMENT ON COLUMN workforce.documents.status                IS 'Document lifecycle status. Valid transitions: PENDING→UPLOADED, UPLOADED→ACTIVE, ACTIVE→REPLACED, ACTIVE→EXPIRED, EXPIRED→REPLACED';
COMMENT ON COLUMN workforce.documents.updated_at            IS 'Timestamp of last state transition in UTC';
COMMENT ON COLUMN workforce.documents.updated_by            IS 'Keycloak user ID of the actor who performed the last state transition';
COMMENT ON COLUMN workforce.documents.uploaded_at           IS 'Timestamp when upload was confirmed by the client - null until confirmed';
COMMENT ON COLUMN workforce.documents.version               IS 'Optimistic locking version for concurrent replacement control';