-- comment: create the availability_log table to maintain an immutable audit trail of agent availability transitions
CREATE TABLE workforce.availability_log (
    id              UUID        NOT NULL DEFAULT gen_random_uuid(),
    agent_id        UUID        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    from_status     VARCHAR(20) NOT NULL,
    reason          TEXT,
    to_status       VARCHAR(20) NOT NULL,

    CONSTRAINT pk_availability_log
        PRIMARY KEY (id),

    CONSTRAINT fk_availability_log_agent
        FOREIGN KEY (agent_id)
            REFERENCES workforce.agents (id)
            ON DELETE RESTRICT
);

-- comment: create indexes for the availability_log table
CREATE INDEX idx_availability_log_agent      ON workforce.availability_log (agent_id);
CREATE INDEX idx_availability_log_created_at ON workforce.availability_log (created_at);

-- comment: add table and column comments for the availability_log table
COMMENT ON TABLE workforce.availability_log IS
    'Immutable append-only audit trail of every agent availability status transition. '
        'No updates or deletes. One record per transition.';

COMMENT ON COLUMN workforce.availability_log.id          IS 'Primary key - UUID generated by application, database default is safety net';
COMMENT ON COLUMN workforce.availability_log.agent_id    IS 'Foreign key to the agent whose availability changed';
COMMENT ON COLUMN workforce.availability_log.created_at  IS 'Timestamp of the transition in UTC - immutable';
COMMENT ON COLUMN workforce.availability_log.from_status IS 'Availability status before the transition';
COMMENT ON COLUMN workforce.availability_log.reason      IS 'Optional context for the transition - required for SUSPENDED and DEACTIVATED transitions';
COMMENT ON COLUMN workforce.availability_log.to_status   IS 'Availability status after the transition';