-- comment: create the location_history table to maintain an immutable audit trail of agent location updates
CREATE TABLE workforce.location_history (
    id          UUID            NOT NULL DEFAULT gen_random_uuid(),
    agent_id    UUID            NOT NULL,
    created_at  TIMESTAMPTZ     NOT NULL,
    h3_index    VARCHAR(20)     NOT NULL,
    latitude    NUMERIC(10,8)   NOT NULL,
    longitude   NUMERIC(11,8)   NOT NULL,
    source      VARCHAR(20)     NOT NULL,

    CONSTRAINT pk_location_history
        PRIMARY KEY (id),

    CONSTRAINT fk_location_history_agent
        FOREIGN KEY (agent_id)
            REFERENCES workforce.agents (id)
            ON DELETE RESTRICT
);

-- comment: add check constraints for the location_history table
ALTER TABLE workforce.location_history
    ADD CONSTRAINT chk_location_history_latitude
        CHECK (latitude >= -90 AND latitude <= 90);

ALTER TABLE workforce.location_history
    ADD CONSTRAINT chk_location_history_longitude
        CHECK (longitude >= -180 AND longitude <= 180);

-- comment: create indexes for the location_history table
CREATE INDEX idx_location_history_agent      ON workforce.location_history (agent_id);
CREATE INDEX idx_location_history_created_at ON workforce.location_history (created_at);

-- comment: add table and column comments for the location_history table
COMMENT ON TABLE workforce.location_history IS
    'Immutable append-only audit trail of every agent location update. '
        'No updates or deletes. One record per location update.';

COMMENT ON COLUMN workforce.location_history.id         IS 'Primary key - UUID generated by application, database default is safety net';
COMMENT ON COLUMN workforce.location_history.agent_id   IS 'Foreign key to the agent whose location was updated';
COMMENT ON COLUMN workforce.location_history.created_at IS 'Timestamp of the location update in UTC - immutable';
COMMENT ON COLUMN workforce.location_history.h3_index   IS 'H3 cell index at resolution 9 at time of update';
COMMENT ON COLUMN workforce.location_history.latitude   IS 'Latitude at time of update';
COMMENT ON COLUMN workforce.location_history.longitude  IS 'Longitude at time of update';
COMMENT ON COLUMN workforce.location_history.source     IS 'Source of the location update - BROWSER_GPS at MVP, ITRACK_DEVICE post-MVP';