-- comment: create the certifications table to track agent compliance certifications
CREATE TABLE workforce.certifications (
      id                  UUID            NOT NULL DEFAULT gen_random_uuid(),
      agent_id            UUID            NOT NULL,
      certification_type  VARCHAR(30)     NOT NULL,
      created_at          TIMESTAMPTZ     NOT NULL,
      created_by          VARCHAR(36)     NOT NULL,
      expires_at          DATE,
      issued_at           DATE            NOT NULL,
      issued_by           VARCHAR(255),
      notes               TEXT,
      reference_number    VARCHAR(100),

      CONSTRAINT pk_certifications
          PRIMARY KEY (id),

      CONSTRAINT fk_certifications_agent
          FOREIGN KEY (agent_id)
              REFERENCES workforce.agents (id)
              ON DELETE RESTRICT
);

-- comment: add check constraints for the certifications table
ALTER TABLE workforce.certifications
    ADD CONSTRAINT chk_certifications_expires_after_issued
        CHECK (expires_at IS NULL OR expires_at > issued_at);

-- comment: create indexes for the certifications table
CREATE INDEX idx_certifications_agent           ON workforce.certifications (agent_id);
CREATE INDEX idx_certifications_type            ON workforce.certifications (certification_type);
CREATE INDEX idx_certifications_expires_at      ON workforce.certifications (expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX idx_certifications_agent_type      ON workforce.certifications (agent_id, certification_type);

-- comment: add table and column comments for the certifications table
COMMENT ON TABLE workforce.certifications IS
    'Agent compliance certifications. MVP: admin-entered manually via onboarding endpoint. '
        'Post-MVP: sourced from Training Context via TrainingCourseCompleted events. '
        'All four certification types carry expiry dates under Kenyan regulatory requirements.';

COMMENT ON COLUMN workforce.certifications.id                 IS 'Primary key - UUID generated by application, database default is safety net';
COMMENT ON COLUMN workforce.certifications.agent_id           IS 'Foreign key to the certified agent';
COMMENT ON COLUMN workforce.certifications.certification_type IS 'Type of certification. NTSA_DRIVING_LICENSE, GOOD_CONDUCT_CERTIFICATE, DEFENSIVE_DRIVING, FIRST_AID';
COMMENT ON COLUMN workforce.certifications.created_at         IS 'Record creation timestamp in UTC - immutable';
COMMENT ON COLUMN workforce.certifications.created_by         IS 'Keycloak user ID of admin who recorded the certification - immutable';
COMMENT ON COLUMN workforce.certifications.expires_at         IS 'Certification expiry date. Null until set by admin. GOOD_CONDUCT_CERTIFICATE: 1 year. DEFENSIVE_DRIVING: 3 years. FIRST_AID: per DOSHS regulations. NTSA_DRIVING_LICENSE: per NTSA renewal cycle';
COMMENT ON COLUMN workforce.certifications.issued_at          IS 'Date the certification was issued by the issuing authority';
COMMENT ON COLUMN workforce.certifications.issued_by          IS 'Issuing authority name e.g. NTSA, National Police Service, AA Kenya';
COMMENT ON COLUMN workforce.certifications.notes              IS 'Optional free-text context provided by the admin recording the certification';
COMMENT ON COLUMN workforce.certifications.reference_number   IS 'Document reference number e.g. NTSA license number. Stored for future NTSA/IPRS verification integration';