-- comment: create the payment_methods table to store agent M-Pesa disbursement details
CREATE TABLE workforce.payment_methods (
   id                   UUID            NOT NULL DEFAULT gen_random_uuid(),
   account_name         VARCHAR(255)    NOT NULL,
   account_reference    VARCHAR(100),
   agent_id             UUID            NOT NULL,
   created_at           TIMESTAMPTZ     NOT NULL,
   created_by           VARCHAR(36)     NOT NULL,
   is_primary           BOOLEAN         NOT NULL DEFAULT FALSE,
   paybill_number       VARCHAR(20),
   payment_method_type  VARCHAR(20)     NOT NULL,
   phone_number         VARCHAR(20),
   till_number          VARCHAR(20),
   updated_at           TIMESTAMPTZ,
   updated_by           VARCHAR(36),
   version              BIGINT          NOT NULL DEFAULT 0,

   CONSTRAINT pk_payment_methods
       PRIMARY KEY (id),

   CONSTRAINT fk_payment_methods_agent
       FOREIGN KEY (agent_id)
           REFERENCES workforce.agents (id)
           ON DELETE RESTRICT
);

-- comment: add check constraints for the payment_methods table
ALTER TABLE workforce.payment_methods
    ADD CONSTRAINT chk_payment_methods_mpesa_personal
        CHECK (
            payment_method_type != 'MPESA_PERSONAL'
                OR (
                phone_number IS NOT NULL
                    AND till_number IS NULL
                    AND paybill_number IS NULL
                    AND account_reference IS NULL
                )
            );

ALTER TABLE workforce.payment_methods
    ADD CONSTRAINT chk_payment_methods_mpesa_till
        CHECK (
            payment_method_type != 'MPESA_TILL'
                OR (
                till_number IS NOT NULL
                    AND phone_number IS NULL
                    AND paybill_number IS NULL
                    AND account_reference IS NULL
                )
            );

ALTER TABLE workforce.payment_methods
    ADD CONSTRAINT chk_payment_methods_mpesa_paybill
        CHECK (
            payment_method_type != 'MPESA_PAYBILL'
                OR (
                paybill_number IS NOT NULL
                    AND account_reference IS NOT NULL
                    AND phone_number IS NULL
                    AND till_number IS NULL
                )
            );

ALTER TABLE workforce.payment_methods
    ADD CONSTRAINT chk_payment_methods_phone_number
        CHECK (phone_number IS NULL OR phone_number ~ '^\+[1-9]\d{1,14}$');

-- comment: create indexes for the payment_methods table
CREATE INDEX idx_payment_methods_agent             ON workforce.payment_methods (agent_id);
CREATE UNIQUE INDEX uq_payment_methods_agent_primary
    ON workforce.payment_methods (agent_id) WHERE is_primary = TRUE;

-- comment: add table and column comments for the payment_methods table
COMMENT ON TABLE workforce.payment_methods IS
    'Agent M-Pesa disbursement details. Queried by Payment and Billing service for agent payouts. '
        'All three M-Pesa payment forms are supported. Mutual exclusivity of fields per type is enforced '
        'at the database level via check constraints.';

COMMENT ON COLUMN workforce.payment_methods.id                  IS 'Primary key - UUID generated by application, database default is safety net';
COMMENT ON COLUMN workforce.payment_methods.account_name        IS 'Registered M-Pesa account name - captured at onboarding for manual verification';
COMMENT ON COLUMN workforce.payment_methods.account_reference   IS 'Paybill account reference - required for MPESA_PAYBILL, null for all other types';
COMMENT ON COLUMN workforce.payment_methods.agent_id            IS 'Foreign key to the agent who owns this payment method';
COMMENT ON COLUMN workforce.payment_methods.created_at          IS 'Record creation timestamp in UTC - immutable';
COMMENT ON COLUMN workforce.payment_methods.created_by          IS 'Keycloak user ID of actor who added this payment method - immutable';
COMMENT ON COLUMN workforce.payment_methods.is_primary          IS 'Exactly one payment method per agent may be primary. Enforced by partial unique index';
COMMENT ON COLUMN workforce.payment_methods.paybill_number      IS 'M-Pesa paybill number - required for MPESA_PAYBILL, null for all other types';
COMMENT ON COLUMN workforce.payment_methods.payment_method_type IS 'M-Pesa payment form. MPESA_PERSONAL, MPESA_TILL, or MPESA_PAYBILL';
COMMENT ON COLUMN workforce.payment_methods.phone_number        IS 'E.164 format Safaricom number - required for MPESA_PERSONAL, null for all other types';
COMMENT ON COLUMN workforce.payment_methods.till_number         IS 'M-Pesa buy goods till number - required for MPESA_TILL, null for all other types';
COMMENT ON COLUMN workforce.payment_methods.updated_at          IS 'Timestamp of last change in UTC';
COMMENT ON COLUMN workforce.payment_methods.updated_by          IS 'Keycloak user ID of actor who performed the last change';
COMMENT ON COLUMN workforce.payment_methods.version             IS 'Optimistic locking version for concurrent update control';