-- comment: create the preferred_agents table to store organisation-scoped ordered agent preferences
CREATE TABLE workforce.preferred_agents (
    id               UUID        NOT NULL DEFAULT gen_random_uuid(),
    agent_id         UUID        NOT NULL,
    branch_id        VARCHAR(36),
    created_at       TIMESTAMPTZ NOT NULL,
    created_by       VARCHAR(36) NOT NULL,
    notes            TEXT,
    organization_id  VARCHAR(36) NOT NULL,
    priority         INTEGER     NOT NULL,
    updated_at       TIMESTAMPTZ,
    updated_by       VARCHAR(36),
    version          BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT pk_preferred_agents
        PRIMARY KEY (id),

    CONSTRAINT fk_preferred_agents_agent
        FOREIGN KEY (agent_id)
            REFERENCES workforce.agents (id)
            ON DELETE RESTRICT
);

-- comment: add check constraints for the preferred_agents table
ALTER TABLE workforce.preferred_agents
    ADD CONSTRAINT chk_preferred_agents_priority
        CHECK (priority > 0);

-- comment: create indexes for the preferred_agents table
CREATE INDEX idx_preferred_agents_agent            ON workforce.preferred_agents (agent_id);
CREATE INDEX idx_preferred_agents_organization     ON workforce.preferred_agents (organization_id);
CREATE INDEX idx_preferred_agents_org_priority     ON workforce.preferred_agents (organization_id, priority);
CREATE UNIQUE INDEX uq_preferred_agents_org_agent
    ON workforce.preferred_agents (organization_id, agent_id);

-- comment: add table and column comments for the preferred_agents table
COMMENT ON TABLE workforce.preferred_agents IS
    'Organisation-scoped ordered agent preference lists. Consumed by Assignment Strategy when '
        'selecting agents for workforce belonging to a given organisation. Priority is a positive integer — '
        'ascending order determines preference. Gaps are permitted, no renumbering required on removal. '
        'organisation_id is a cross-service reference to the Organizations context — no FK constraint.';

COMMENT ON COLUMN workforce.preferred_agents.id               IS 'Primary key - UUID generated by application, database default is safety net';
COMMENT ON COLUMN workforce.preferred_agents.agent_id         IS 'Foreign key to the preferred agent';
COMMENT ON COLUMN workforce.preferred_agents.branch_id        IS 'Optional branch ID for the preferred agent';
COMMENT ON COLUMN workforce.preferred_agents.created_at       IS 'Record creation timestamp in UTC - immutable';
COMMENT ON COLUMN workforce.preferred_agents.created_by       IS 'Keycloak user ID of admin who added this preference - immutable';
COMMENT ON COLUMN workforce.preferred_agents.notes            IS 'Optional context for the preference e.g. familiar with delivery zone';
COMMENT ON COLUMN workforce.preferred_agents.organization_id  IS 'Cross-service reference to the organisation in Organizations context. No FK constraint - validated at application layer';
COMMENT ON COLUMN workforce.preferred_agents.priority         IS 'Positive integer. Ascending order determines preference. Gaps permitted - no renumbering required on removal';
COMMENT ON COLUMN workforce.preferred_agents.updated_at       IS 'Timestamp of last change in UTC';
COMMENT ON COLUMN workforce.preferred_agents.updated_by       IS 'Keycloak user ID of actor who performed the last change';
COMMENT ON COLUMN workforce.preferred_agents.version          IS 'Optimistic locking version for concurrent update control';
